### ISSUE TITLE
Crash prior to preinitialization step in FML

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#1]
So, I gave it a try on 1.10.2 with forge 2088 (is there a version you recommend for AM2?) and no other mods.

This is the result:

http://pastebin.com/mremsViA

Ignore the donutcraft bits in the log; I just used that to get something I could launch with atlauncher, emptied out all the mods and config before starting.

**Comment by esotericist** [comment]
Just now tried it with 2094, same thing.

**Comment by esotericist** [comment]
So, after that, I realized that the current build of forge that's flagged as "recommended" on their site is 2011 (although many of my mods will not successfully run with that), so I thought I'd give it a try as well.

http://pastebin.com/2ZPZRzys

It crashes at a different point, but ... well, still crashy.

**Comment by EdwinMindcraft** [comment]
It's still in a 1.9.4 state for now. Until I fix the whole mod.

**Comment by esotericist** [comment]
Ah, okay. I'm used to 1.9.4 mods 'just working' on 1.10.2, didn't occur to me that might be a problem.

**Comment by EdwinMindcraft** [comment]
Nah there's just a load order problem that I'll have to fix. My data manager is loading after default minecraft classes whereas it should be loading way before.

**Comment by esotericist** [comment]
So, for clarity, is there an environment this should currently work in? 1.9.4 and some specific version of forge?

Or does it need to wait until you address that load order issue?

**Comment by EdwinMindcraft** [comment]
It should work on 1.9.4 Recommended+ I'm currently working on the load order problem though.

**Comment by EdwinMindcraft** [comment]
Fixed in 2.0.1, should be in dropbox soon
