### ISSUE TITLE
Player AM2 stats erratic after death

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#10]
Forge 2094, AM2 2.0.6, jei_1.10.2-3.9.0.246 present. Testing performed in SSP.

Sometimes after death, player state with regards to AM2 enters strange states. Burnout max being reduced to 1, current mana being greater than max mana, no AM2 UI at all unless entering creative mode...

Sometimes this corrects itself on casting a spell, sometimes it doesn't.

**Comment by EdwinMindcraft** [comment]
Yep that's my buggy data manager... I'll need to schedule a full update after respawn
