### ISSUE TITLE
Flickers unexpectedly proliferate?

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#11]
Forge 2094, AM2 2.0.6, jei_1.10.2-3.9.0.246 present. Testing performed in SSP.

I'm uncertain whether this is a bug, an oversight during the significant rewriting necessary for the port, or an intentional change in behavior.

When playing AM2 on 1.7.10, I never once saw a flicker. I knew abstractly they existed, but they never manifested anywhere that I could see during actual play, and I never bothered making a flicker lure. (I had golems, why would I want flickers, right?)

In the 1.10.2 port of AM2, flickers are **everywhere**. I have on several occasions had three to eight of them in view just standing in place, looking in a single direction out over my farm.

Are they supposed to manifest without lures? I had previously been under the impression they either wouldn't be present without a lure, or wouldn't be visible without some other tool.

If they are supposed to manifest, are they supposed to be easy to find? Considering that lures require essence to operate, they seem like a 'bad deal' when you can so readily find flickers simply just by walking around.

**Comment by EdwinMindcraft** [comment]
I did do flicker passive gen since the code was here... But you're right : They shouldn't proliferate as much as they do. And I'll buff the Lure to make it actually worth it.
