### ISSUE TITLE
Purchased spell components not reliably showing up in spell compendium

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#14]
AM2 2.0.7.

It looks like things I bought in the occulus (not sure at what point the problem started, but I expect it's related to the relatively recent edits to the data handler) aren't showing up in the Compendium. They are available in the inscription table, they just don't show up in the book unless I turn on creative mode.

New saves get nothing in the compendium, my survival run has only a handful of older things in it (from a few versions ago)

**Comment by esotericist** [comment]
Update: it looks like restarting causes it to correctly sync the compendium.

**Comment by EdwinMindcraft** [comment]
Looks like another sync issue to me...
