### ISSUE TITLE
Item duplication with Item Transport flicker focus and Storage Drawers

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#17]
AM2 2.0.8, forge 2094.

Preliminary report from my heavily modded survival world: Storage Drawer with 32 or more stone hoes in it (I'm automating Progressive Automation planters). Whenever the flickers would pull from that drawer, the contents of that drawer would not decrease.

This did not happen with 31 or less stone hoes, and it did not happen with actual stacks of items (32 stacks of cobblestone worked fine). I was also able to duplicate it with a drawer of 32 iron axes I quickly placed in creative.

**Comment by EdwinMindcraft** [comment]
Well I think it might be reproducible with any kind on one-per-stack items... Still got to figure out why tho

**Comment by EdwinMindcraft** [comment]
I might create a WTF tag soon...

**Comment by TheIcyOne** [comment]
Does this happen with vanilla chests? You'd need I think a double chest to reach the 32 required. It'd also be interesting to see what happens with things that don't stack to 64, but still stack like eggs or snowballs.
