### ISSUE TITLE
Oak Felling flicker focus not harvesting trees

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#18]
AM2 2.0.8, forge 2094, confirmed with no other mods present.

Oak Felling flicker focus, with and without etherium, disregards nearby trees. First tried with mod trees (from biomes o plenty) then with regular oak, and finally tested in my AM2-only folder.

![2016-10-17_19 51 47](https://cloud.githubusercontent.com/assets/1569754/19462636/29c1bee0-94a3-11e6-88ac-f017784efa32.png)

**Comment by esotericist** [comment]
I'll slowly work my way through trying all of them, I'm just only doing these things as they're meaningful in my survival world. :)

And yes, I'm just powering through the FPS issue, because the AM2 item transport solves problems that are super frustrating to deal with otherwise.

**Comment by Growlith1223** [comment]
it's not actually disregarding it, the for loop that is checking for trees isn't being fully completed, for some reason it only sees the outer borders. if you put a tree in one of the 4 corners(can't remember which) on the 6 block radius, you'll see that it breaks it, i'll post a fix for it if it isn't fixed before then

**Comment by esotericist** [comment]
The fix you have for this in 7452ee7 seems incomplete.
![2016-10-22_22 21 43](https://cloud.githubusercontent.com/assets/1569754/19624345/12b5f28c-98a6-11e6-8f2b-b513b32c3be6.png)

Unless it's not actually intended to get the whole tree?

**Comment by Growlith1223** [comment]
this is because it's checking the same block over and over, in the DestroyTree for loop, when you break a log, add that position to a list, then when it hits that block again, do a Continue

**Comment by Growlith1223** [comment]
http://pastebin.com/UNKAzrKv this is what i've done in my code

**Comment by Growlith1223** [comment]
http://pastebin.com/Fd8S89FT this is what i've done in my code

**Comment by Growlith1223** [comment]
correction, it's not because of the same block recurrence, it's because of blockStates, it doesn't see that vertical and horizontal wood blocks are the same
