### ISSUE TITLE
Can't purchase skills/talents in occulus in survival

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#2]
minecraft 1.10.2, forge 2094, AM2 2.0.1, no other mods present, SSP.

When I buy something in the occulus, it briefly shows as purchased, lighting up both what I purchased and the items for which it's a pre-requisite, then shortly thereafter (ranging from a fraction of a second to approximately two seconds) it darkens again, as if it had not been purchased. The component/talent does not show up in the compendium, and the skill point is returned.

Seems like the server isn't accepting the purchase event?

**Comment by EdwinMindcraft** [comment]
Either server side error or an error in my new data system...

**Comment by EdwinMindcraft** [comment]
Should be fixed in 2.0.2

**Comment by esotericist** [comment]
Thanks so much! I'll try to actually begin a legitimate play of AM2 later today, and see how far that gets me.
