### ISSUE TITLE
Unable to pair crafting altar with power sources

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#21]
AM2 2.0.8 (verified with your release, not my edits)
![2016-10-26_02 47 14](https://cloud.githubusercontent.com/assets/1569754/19721297/85577acc-9b26-11e6-9793-4b8c70359ca8.png)

Every configuration and positioning I've tried, with and without the obelisk having power, with a mana battery instead of an obelisk, has resulted in the "No path was found" error.

**Comment by esotericist** [comment]
Notably, I _can_ pair the obelisk with a mana battery, and it works correctly with power visibly transferring to the mana battery with magitech goggles worn.

I also tried essence conduits.

**Comment by EdwinMindcraft** [comment]
(Finally) fixed in the last 1.10.2 commit.
