### ISSUE TITLE
[1.10.2] Spells no longer work in a Spell Book

### ISSUE THREAD

**Issue by SjetCraft** [EdwinMindcraft/ArsMagica2#29]
Spells no longer work in a spell book.
On retrieving spells from spell book, spells were non functional.

TLDR: Spell Books wiping spell information.

Using [`7755490`](https://github.com/EdwinMindcraft/ArsMagica2/commit/77554906ce92858a75075599adb818f0fc4fadc9)

`/am2 updatespells` worked successfully on old spells.

**Comment by EdwinMindcraft** [comment]
Try to ping me on Discord if you get an issue, that's the only way your going to be sure I saw it :D

**Comment by EdwinMindcraft** [comment]
Closed with last commit
