### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by JVanhook** [EdwinMindcraft/ArsMagica2#3]
Im using 2.02 AM2 mod on MC 1.10.2 with forge 12.18.1.2095. I have leveled up and my magic level is 5 however i have not attained anymore skill points at all

**Comment by EdwinMindcraft** [comment]
Looks like I forgot a functionality...

**Comment by JVanhook** [comment]
I look forward to the next revision

**Comment by EdwinMindcraft** [comment]
Should be done once I gain access to a computer, 5-6 hours.

**Comment by JVanhook** [comment]
ill take a look when i wake up in about 8 hrs

**Comment by EdwinMindcraft** [comment]
Should be availaible in the next version.
