### ISSUE TITLE
Level Shenanigans

### ISSUE THREAD

**Issue by radzo73** [EdwinMindcraft/ArsMagica2#38]
So, a while back, on Discord, I found out about /am2 magiclevel, and it apparently went up to 99.
However, I didn't stop there.
99? Check.
999? Check.
9999? Check.
2099999999? Pretty much the maximum.
![2018-04-11_07 50 16](https://user-images.githubusercontent.com/26673668/38675648-6c0a3358-3e26-11e8-87ac-4cc375873ed4.png)
However, in a course of a few minutes, this happens.
[crash-2018-04-11_08.00.55-server.txt](https://github.com/EdwinMindcraft/ArsMagica2/files/1902975/crash-2018-04-11_08.00.55-server.txt)

**Comment by EdwinMindcraft** [comment]
The average level is now 2099999999, multiply it by two and you are WAY over the 2^31 needed to go negative. I'm adding a Math.min between that and integer.max_value.
