### ISSUE TITLE
All the items are gone.

### ISSUE THREAD

**Issue by radzo73** [EdwinMindcraft/ArsMagica2#39]
Sorta self-explanatory.
~~there aren't even commands such as /amuicfg~~
I'm using version v1.5.0C-10 ~~even though the download says that it's C-9 but whatever~~
![2018-04-16_07 48 42](https://user-images.githubusercontent.com/26673668/38807445-9923294a-414a-11e8-9053-f36bf88cf2cc.png)

**Comment by EdwinMindcraft** [comment]
Updated it, try redownloading. If it doesn't work, then I'm lost
