### ISSUE TITLE
Witchwood saplings not dropping from witchwood leaves

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#4]
I know the drop rate is intended to be low for witchwood saplings, but I doubt it's intended to be 'never'. I've tested a few thousand runs of wizards autumn (with and without prosperity), and eventually resorted to trying a bunch of cycles of copying a witchwood tree and then removing the wood in order to prompt leaf decay.

I recorded a handful of cycles of this.
https://youtu.be/-lv-Eyge_jU

Forge 2094, initial testing was under AM2 2.0.1 (this was how I discovered issue #2), confirmed still present under 2.0.3. Other mod present only for last stages of testing (above video): FastLeafDecay-v11.jar

**Comment by esotericist** [comment]
... took another look over here...

https://github.com/EdwinMindcraft/ArsMagica2/blob/1.9-Rework/src/main/java/am2/blocks/BlockWitchwoodLeaves.java

... Am I reading it right that it's a 1 in 300 for something to drop, then a further 1 in 300 for it to be a quantity of 1, otherwise a quantity of 0?

If that's the actual problem, I suppose it's technically an upstream issue. Baffling, though.

**Comment by EdwinMindcraft** [comment]
You tracked down the issue... I may or may not have done some shit here...

**Comment by esotericist** [comment]
The logic that looks like it's a 1 in 90,000 chance for sapling is from mithion's repo.

**Comment by EdwinMindcraft** [comment]
I used most of Mithion's code for the port.

**Comment by esotericist** [comment]
I'm just saying, this might not actually be your fault. :D

I mean, I'd totally be down with you fixing it, since I kinda like having witchwood and aum something resembling renewable but we don't really have a clear reference point for what it "should" be from the original material.

Beyond probably not this, I mean.

**Comment by EdwinMindcraft** [comment]
Will do :)

**Comment by esotericist** [comment]
Minor buff. ;)

**Comment by esotericist** [comment]
Well, crud. I got a forge build environment together last night for an unrelated project, so I decided to build this to give it a try, and I'm still not seeing any witchwood saplings. 

Doing more research, and I think we both may have misunderstood how the relevant parts of the code work for the leaf drops.

More thoughts once I have a better handle on it.

**Comment by esotericist** [comment]
The pull request is the result of a couple of hours of me flailing blindly. I'm no java programmer, and I especially do not understand this environment. So this might still be wrong, I only know it worked for me.

**Comment by esotericist** [comment]
Just got around to testing it, and it works! Hooray!

Thanks so much.
