### ISSUE TITLE
Dryads exhibit a marked lack of behavior

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#7]
Forge 2094, AM2 2.0.6, jei_1.10.2-3.9.0.246 present. Testing performed in SSP.

Dryads stand in place without moving or looking around. The only motion they make is adjusting their body to match their head facing immediately after spawning, thereafter they are unresponsive.

**Comment by EdwinMindcraft** [comment]
EntityDryad L40 : isAIDisabled() {return true}... Yay I did shit again...

**Comment by esotericist** [comment]
Whoops.

Well, could be worse. I found this last night while tracing logic in mapwriter, trying to improve my hacked version of it: https://github.com/esotericist/mapwriter/blob/1.10.2/src/main/java/mapwriter/region/MwChunk.java#L223
