### ISSUE TITLE
Crafting Altar creates invalid spells on early completion attempt

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#8]
Forge 2094, AM2 2.0.6, jei_1.10.2-3.9.0.246 present. Testing performed in SSP.

If you start the crafting process with a blank rune, at any point from then up until you have successfully entered all correct items, you can drop in a parchment and it will "complete" the spell, giving you a spell item that to all appearances looks like it succeeded, except for the fact it has a mana cost of 0.

I spent quite a long bit of time trying to figure out why my touch light spell wasn't working before I realized I never dropped in the torch, but it "completed" anyway.

**Comment by EdwinMindcraft** [comment]
I'll have to check the system but... I guess it was kinda of intended by Mithion but it used to say malformed spell or something...

**Comment by esotericist** [comment]
If it said malformed spell, and didn't bring up the "finalize name/select icon" screen on use, that'd help. It's that it APPEARS to work.

**Comment by EdwinMindcraft** [comment]
I'll add an NBT Boolean that'll handle spell validity.
