### ISSUE TITLE
Touch Light behaves erratically

### ISSUE THREAD

**Issue by esotericist** [EdwinMindcraft/ArsMagica2#9]
Forge 2094, AM2 2.0.6, jei_1.10.2-3.9.0.246 present. Testing performed in SSP.

This one is harder to reproduce, I've had mixed results in testing worlds.

Sometimes touch light will burn mana, but simply fail to produce a light source in conditions where projectile light would succeed. I haven't been able to find any particular pattern other than it seems to be 'streaky', where it will not work for a while, then if it is working, you might get a few casts in a row where it does successfully place lights.

Projectile light works fine, and the other touch spells I tested (dig, fire damage) worked fine.

**Comment by EdwinMindcraft** [comment]
Basically it seams like light is buggy

**Comment by esotericist** [comment]
Projectile light works pretty much fine, though, is the weird thing

**Comment by esotericist** [comment]
Okay, more info. While chasing down another problem, I tried 'projectile aoe light', and it works basically exactly as reliably as touch light. Which is to say, not.

More to the point, though, I think there might be a deeper problem than light specifically, because 'projectile AOE dig' behaves REALLY weird, while 'touch AOE dig' does not.

Seems like there's something odd going on with targeting in general?

**Comment by EdwinMindcraft** [comment]
AoE targeting is weird, basically it depends on the face hit...

**Comment by esotericist** [comment]
Well, when I used Touch AoE Dig, it behaved as expected; face touched determined AOE orientation, centered on the block touched. That's fine.

When I used Projectile AoE Dig, it only sometimes managed to dig at all, and when it did, it was not centered on the block hit, but generally Y+1. The off-by-one is probably easy to fix, but the fact it sometimes wouldn't fire is more concerning.
